### PR TITLE
Basic work for Python 3 support

### PR DESCRIPTION
**Pull request by SunilMohanAdapa**
Highlights:

- Retain support for Python 2.
- Minimally invasive so that it is easy to verify for accuracy.
- Broken down into individual patches that can be cherry picked without others (for the most part).

Unfortunately, I could not test this well enough.

### CODE REVIEW

**Comment by SunilMohanAdapa** [comment]
If this change is considered disruptive, perhaps it can be merged into a python3 branch that can later be merged into master after perceived stability.

**Comment by BjarniRunar** [comment]
Thank you for doing this. I'm not ignoring you, but I haven't yet found time to work on this. It's on my list.

**Comment by BjarniRunar** [comment]
Update: I am working on reviewing and merging this in my local branch.

**Comment by SunilMohanAdapa** [comment]
@BjarniRunar , thank you for looking into it. There is definitely more work needed after this is merged especially related to binary/unicode strings. Hopefully, it won't be much. I will try to hang out on the IRC channel but I am travelling for a week and may not be immediately available.

**Comment by lzap** [comment]
Guys, PageKite was removed from Fedora Rawhide. But it should be pretty easy for me to return it back once a new Python3 release is out.

**Comment by BjarniRunar** [comment]
Thanks for the update, @lzap  :-)

**Pull request merged**
